from .ProductList import *
from .CategoryCreate import *
from .CategoryDelete import *
from .CategoryUpdate import *
from .CategoryList import *
from .ProductCreate import *
from .ProductUpdate import *
from .ProductDelete import *
from .ProductVariantCreate import *
from .ProductVariantUpdate import *
from .ProductVariantDelete import *
from .ProductVariantList import *
from .SizeCreate import *
from .SizeUpdate import *
from .SizeDelete import *   
from .SizeList import *
from .ColorCreate import *
from .ColorUpdate import *
from .ColorDelete import *
from .ColorList import *
from .BrandCreate import *
from .BrandUpdate import *
from .BrandDelete import *
from .BrandList import *
from .MediaFileCreate import *
from .MediaFileUpdate import *
from .MediaFileDelete import *
from .MediaFileList import *